/*
 * butled.c
 *
 *  Created on: Sep 10, 2023
 *      Author: Sx107
 */

#include <butled.h>
#include <main.h>

uint8_t but_pstat[5] = {0, 0, 0, 0, 0};
uint8_t but_rel[5] = {0, 0, 0, 0, 0};

GPIO_TypeDef* const BUT_PORT[5] = 	{GPIOB, GPIOB, GPIOF, GPIOF, GPIOB};
const uint32_t BUT_PIN[5] = 			{GPIO_IDR_12, GPIO_IDR_14, GPIO_IDR_6, GPIO_IDR_7, GPIO_IDR_6};

GPIO_TypeDef* const BUTLED_PORT[5] = {GPIOB, GPIOB, GPIOA, GPIOA, GPIOB};
const uint32_t BUTLED_ON[5] = {GPIO_BSRR_BS_13, GPIO_BSRR_BS_15, GPIO_BSRR_BS_12, GPIO_BSRR_BS_15, GPIO_BSRR_BS_3};
const uint32_t BUTLED_OFF[5] = {GPIO_BSRR_BR_13, GPIO_BSRR_BR_15, GPIO_BSRR_BR_12, GPIO_BSRR_BR_15, GPIO_BSRR_BR_3};

void butled_configure() {
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	RCC->AHBENR |= RCC_AHBENR_GPIOBEN;
	RCC->AHBENR |= RCC_AHBENR_GPIOFEN;

	// Buttons: PB12, PB14, PF6, PF7, PB6 (Set to GPIO Input with pullup, minimal speed)
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER12_Msk, 0);
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER14_Msk, 0);
	MODIFY_REG(GPIOF->MODER, GPIO_MODER_MODER6_Msk, 0);
	MODIFY_REG(GPIOF->MODER, GPIO_MODER_MODER7_Msk, 0);
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER6_Msk, 0);

	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEEDR12_Msk, 0);
	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEEDR14_Msk, 0);
	MODIFY_REG(GPIOF->OSPEEDR, GPIO_OSPEEDR_OSPEEDR6_Msk, 0);
	MODIFY_REG(GPIOF->OSPEEDR, GPIO_OSPEEDR_OSPEEDR7_Msk, 0);
	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEEDR6_Msk, 0);

	MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPDR12_Msk, 0b01 << GPIO_PUPDR_PUPDR12_Pos);
	MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPDR14_Msk, 0b01 << GPIO_PUPDR_PUPDR14_Pos);
	MODIFY_REG(GPIOF->PUPDR, GPIO_PUPDR_PUPDR6_Msk, 0b01 << GPIO_PUPDR_PUPDR6_Pos);
	MODIFY_REG(GPIOF->PUPDR, GPIO_PUPDR_PUPDR7_Msk, 0b01 << GPIO_PUPDR_PUPDR7_Pos);
	MODIFY_REG(GPIOB->PUPDR, GPIO_PUPDR_PUPDR6_Msk, 0b01 << GPIO_PUPDR_PUPDR6_Pos);

	// Button LEDS: PB13, PB15, PA12, PA15, PB3 (Set to GPIO Output Push-Pull min speed)
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER13_Msk, 0b01 << GPIO_MODER_MODER13_Pos);
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER15_Msk, 0b01 << GPIO_MODER_MODER15_Pos);
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER12_Msk, 0b01 << GPIO_MODER_MODER12_Pos);
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER15_Msk, 0b01 << GPIO_MODER_MODER15_Pos);
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER3_Msk,  0b01 << GPIO_MODER_MODER3_Pos);

	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEEDR13_Msk, 0);
	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEEDR15_Msk, 0);
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEEDR12_Msk, 0);
	MODIFY_REG(GPIOA->OSPEEDR, GPIO_OSPEEDR_OSPEEDR15_Msk, 0);
	MODIFY_REG(GPIOB->OSPEEDR, GPIO_OSPEEDR_OSPEEDR3_Msk, 0);

	MODIFY_REG(GPIOB->OTYPER, GPIO_OTYPER_OT_13, 0);
	MODIFY_REG(GPIOB->OTYPER, GPIO_OTYPER_OT_15, 0);
	MODIFY_REG(GPIOA->OTYPER, GPIO_OTYPER_OT_12, 0);
	MODIFY_REG(GPIOA->OTYPER, GPIO_OTYPER_OT_15, 0);
	MODIFY_REG(GPIOB->OTYPER, GPIO_OTYPER_OT_3, 0);

	GPIOB->BSRR |= GPIO_BSRR_BR_13;
	GPIOB->BSRR |= GPIO_BSRR_BR_15;
	GPIOA->BSRR |= GPIO_BSRR_BR_12;
	GPIOA->BSRR |= GPIO_BSRR_BR_15;
	GPIOB->BSRR |= GPIO_BSRR_BR_3;
}

void butled_on(uint8_t butled) {
	BUTLED_PORT[butled]->BSRR |= BUTLED_ON[butled];
}

void butled_off(uint8_t butled) {
	BUTLED_PORT[butled]->BSRR |= BUTLED_OFF[butled];
}

uint8_t but_check(uint8_t butled) {
	return ((BUT_PORT[butled]->IDR) & BUT_PIN[butled]) != 0 ? 0 : 1;
}

void but_update() {
	for(uint8_t i = 0; i < 5; i++) {
		but_rel[i] = 0;
		uint8_t b = but_check(i);
		if(!b && but_pstat[i]) {but_rel[i] = 1;}
		but_pstat[i] = b;
	}
}

uint8_t but_released(uint8_t but) {
	return but_rel[but];
}
