/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <main.h>
#include <clock.h>
#include <pwm.h>
#include <butled.h>
#include <adc.h>
#include <tick.h>
#include <i2c.h>
#include <eeprom.h>
#include <synth.h>
#include <midi.h>
#include <lfo.h>

#define EEPROM_SIZE 196
#define EEPROM_ALIGNED_SIZE 208
const uint8_t eeprom_defaults[EEPROM_ALIGNED_SIZE] = {
197, 8, 72, 8, 149, 9, 120, 7, 17, 14, 102, 10, 255, 7, 255, 7, 255, 7, 255, 7, 255, 7, 255, 7, 166, 4, 12, 7, 18, 9, 79, 4, 164, 4, 104, 6, 1, 0, 0, 0, 8, 0, 0, 0, 52, 0, 0, 32,			// Preset M1
165, 8, 72, 8, 212, 9, 75, 4, 0, 0, 104, 7, 255, 7, 255, 7, 104, 6, 179, 10, 255, 7, 255, 7, 255, 7, 255, 7, 255, 7, 255, 7, 255, 7, 255, 7, 1, 0, 0, 0, 4, 0, 0, 0, 52, 0, 0, 32,			// Preset M2
134, 7, 65, 8, 186, 8, 222, 2, 117, 6, 120, 8, 0, 0, 255, 15, 255, 15, 255, 15, 110, 7, 113, 4, 255, 15, 143, 8, 255, 15, 255, 7, 66, 11, 255, 7, 1, 0, 0, 0, 2, 0, 0, 0, 52, 0, 0, 32,		// Preset M3
197, 8, 72, 8, 149, 9, 120, 7, 17, 14, 102, 10, 255, 7, 255, 7, 255, 7, 255, 7, 255, 7, 255, 7, 166, 4, 12, 7, 18, 9, 79, 4, 164, 4, 104, 6, 1, 0, 0, 0, 8, 0, 0, 0, 52, 0, 0, 32,			// Preset X
0xFA, 0xCE, // Check
0xFF,		// Midi channel
0x00		// Preset X loaded
};

int main(void)
{
	RCC->APB1ENR |= RCC_APB1ENR_PWREN;
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;

	clock_configure();

	butled_configure();
	_delayMs(10);
	adc_configure();
	i2c1_init();

	 if(but_check(BUTLED_SAVE) && but_check(BUTLED_DRONE)) {
		uint8_t make_reset = 1;
		for(uint16_t i = 0; i < 1000; i++) {
			if(!(but_check(BUTLED_SAVE) && but_check(BUTLED_DRONE))) {
				make_reset = 0;
				break;
			}
			_delayMs(1);
		}

		if(make_reset) {
			eeprom_write8(EEPROM_HAS_PRESET3, 0);
			butled_animation = 0b11111;
			butled_timer = 500;
		}
	} else if(but_check(BUTLED_M1) && but_check(BUTLED_M2) && but_check(BUTLED_M3)) {
		uint8_t make_reset = 1;
		for(uint16_t i = 0; i < 1000; i++) {
			if(!(but_check(BUTLED_M1) && but_check(BUTLED_M2) && but_check(BUTLED_M3))) {
				make_reset = 0;
				break;
			}
			_delayMs(1);
		}

		if(make_reset) {
			for(uint16_t i = 0; i < EEPROM_ALIGNED_SIZE; i+= 16) {
				eeprom_write_buffer(i, eeprom_defaults + i, 16);
				_delayMs(20);
			}
			butled_animation = 0b11111;
			butled_timer = 500;
		}
	}

	lfo_sync_configure();
	_midi_own_channel = eeprom_read8(EEPROM_MIDI_CHAN);
	midi_configure();
	synth_reset_midi();

	_delayMs(10);
	if(eeprom_read8(EEPROM_HAS_PRESET3)) {
		synth_load_preset(3);
	} else {
		_synth_drone = 1;
		for(uint8_t i = 0; i < 9; i++) {
			_synth_knob_active[i] = 1;
			//_synth_knob[i] = adcData[i];
		}
	}


	tick_configure();

	_delayMs(10);
	pwm_configure();




    /* Loop forever */
	for(;;) {
		__WFI();
	}
}
