/*
 * pwm.c
 *
 *  Created on: Jan 10, 2022
 *      Author: Sx107
 */

#include <pwm.h>
#include <main.h>

 volatile uint32_t* const PWM_LEDS[6] = {&PWM_LED1, &PWM_LED2, &PWM_LED3, &PWM_LED4, &PWM_LED5, &PWM_LED6};

#include <lfo.h>
#include <synth.h>
//#include <adc.h>

void pwm_configure() {
	/*
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER8_0;
	GPIOA->OSPEEDR |= (3 << GPIO_OSPEEDR_OSPEEDR8_Pos);
	GPIOA->BSRR |= GPIO_BSRR_BS_8;
	*/
	NVIC_SetPriority(TIM1_BRK_UP_TRG_COM_IRQn, 0);
	NVIC_EnableIRQ(TIM1_BRK_UP_TRG_COM_IRQn);

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	RCC->AHBENR |= RCC_AHBENR_GPIOBEN;

	// Set A9-A11 pins to Timer CH1-CH4
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER8_Msk, 0b10 << GPIO_MODER_MODER8_Pos);	// AF
	MODIFY_REG(GPIOA->AFR[1], GPIO_AFRH_AFRH0_Msk, 2 << GPIO_AFRH_AFRH0_Pos); 	// AF2
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER9_Msk, 0b10 << GPIO_MODER_MODER9_Pos);	// AF
	MODIFY_REG(GPIOA->AFR[1], GPIO_AFRH_AFRH1_Msk, 2 << GPIO_AFRH_AFRH1_Pos); 	// AF2
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER10_Msk, 0b10 << GPIO_MODER_MODER10_Pos);	// AF
	MODIFY_REG(GPIOA->AFR[1], GPIO_AFRH_AFRH2_Msk, 2 << GPIO_AFRH_AFRH2_Pos); 	// AF2
	MODIFY_REG(GPIOA->MODER, GPIO_MODER_MODER11_Msk, 0b10 << GPIO_MODER_MODER11_Pos);	// AF
	MODIFY_REG(GPIOA->AFR[1], GPIO_AFRH_AFRH3_Msk, 2 << GPIO_AFRH_AFRH3_Pos); 	// AF2

	// Configure Timer 1

	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	TIM1->PSC = 0;
	TIM1->ARR = 1023;
	TIM1->RCR = 3;
	TIM1->DIER |= TIM_DIER_UIE;
	TIM1->CCMR1 |= (0b110 << TIM_CCMR1_OC1M_Pos) | (0b110 << TIM_CCMR1_OC2M_Pos);
	TIM1->CCMR2 |= (0b110 << TIM_CCMR2_OC3M_Pos) | (0b110 << TIM_CCMR2_OC4M_Pos);
	TIM1->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E | TIM_CCER_CC4E;
	TIM1->CR1 |= TIM_CR1_ARPE;
	TIM1->BDTR |= TIM_BDTR_MOE;
	TIM1->CR1 |= TIM_CR1_CEN;

	TIM1->CCR1 = 512;
	TIM1->CCR2 = 512;
	TIM1->CCR3 = 512;
	TIM1->CCR4 = 512;

	// Set PB1 to CH4, PB4 to CH1, PB5 to CH2
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER1_Msk, 0b10 << GPIO_MODER_MODER1_Pos);	// AF
	MODIFY_REG(GPIOB->AFR[0], GPIO_AFRL_AFRL1_Msk, 1 << GPIO_AFRL_AFRL1_Pos); 	// AF1
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER4_Msk, 0b10 << GPIO_MODER_MODER4_Pos);	// AF
	MODIFY_REG(GPIOB->AFR[0], GPIO_AFRL_AFRL4_Msk, 1 << GPIO_AFRL_AFRL4_Pos); 	// AF1
	MODIFY_REG(GPIOB->MODER, GPIO_MODER_MODER5_Msk, 0b10 << GPIO_MODER_MODER5_Pos);	// AF
	MODIFY_REG(GPIOB->AFR[0], GPIO_AFRL_AFRL5_Msk, 1 << GPIO_AFRL_AFRL5_Pos); 	// AF1

	// Configure Timer 3

	RCC->APB1ENR |= RCC_APB1ENR_TIM3EN;
	TIM3->PSC = 0;
	TIM3->ARR = 1023;
	//TIM3->DIER |= TIM_DIER_UIE;
	TIM3->CCMR1 |= (0b110 << TIM_CCMR1_OC1M_Pos) | (0b110 << TIM_CCMR1_OC2M_Pos);
	TIM3->CCMR2 |= (0b110 << TIM_CCMR2_OC4M_Pos);
	TIM3->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC4E;
	TIM3->CR1 |= TIM_CR1_ARPE;
	TIM3->CR1 |= TIM_CR1_CEN;

	TIM3->CCR1 = 512;
	TIM3->CCR2 = 512;
	TIM3->CCR4 = 512;
}

void TIM1_BRK_UP_TRG_COM_IRQHandler(void) {
	GPIOC->BSRR |= GPIO_BSRR_BS_13;
	lfo_process();
	synth_process();

	GPIOC->BSRR |= GPIO_BSRR_BR_13;
	TIM1->SR &= ~TIM_SR_UIF;
}

